/// Flutter icons Bottom_nav_bar
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottom_nav_bar
///      fonts:
///       - asset: fonts/Bottom_nav_bar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bottom_nav_bar {
  Bottom_nav_bar._();

  static const _kFontFam = 'Bottom_nav_bar';
  static const String? _kFontPkg = null;

  static const IconData card = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scan = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
